services:
  ubuntu-ssh-server-2221:
    build:
      dockerfile: ./Dockerfile.test
      context: .
    image: ubuntu-ssh-server:latest
    ports:
      - 2221:2222

  ubuntu-ssh-server-2222:
    build:
      dockerfile: ./Dockerfile.test
      context: .
    image: ubuntu-ssh-server:latest
    ports:
      - 2222:2222

  ubuntu-ssh-server-2223:
    build:
      dockerfile: ./Dockerfile.test
      context: .
    image: ubuntu-ssh-server:latest
    ports:
      - 2223:2222

  ubuntu-ssh-server-2224:
    build:
      dockerfile: ./Dockerfile.test
      context: .
    image: ubuntu-ssh-server:latest
    ports:
      - 2224:2222

  binfmt:
    image: tonistiigi/binfmt
    container_name: binfmt
    restart: "no"
    privileged: true
    network_mode: bridge
    command: --install all

  openwrt-router-2229:
    depends_on:
      binfmt:
        condition: service_completed_successfully
    build:
      dockerfile: ./Dockerfile.test-openwrt
      context: .
    image: openwrt-router:latest
    ports:
      - 2229:22
